name: Verify-Output

inputs:
  client-folder:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      shell: bash
      id: nvm
      working-directory: ./verify

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "name=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ./verify

    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --nonInteractive --frozen-lockfile --prefer-offline
      shell: bash
      working-directory: ./verify

    - name: Run
      run: yarn start -- ../clients/${{ inputs.client-folder }}
      shell: bash
      working-directory: ./verify
