[tool.poetry]
name = "python-client-readiness"
description = ""
authors = []
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^5.4.1"
importlib-metadata = "^4.8.1"
polywrap-client = "^0.1.0a29"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
